### PR TITLE
pq-compile, and license header fixes

### PR DESCRIPTION
**Pull request by tgbugs**

### CODE REVIEW

**Review by monnier — COMMENTED** [review]
The email address in `Author: Tom Gillespie tgbugs@gmail.com` should be wrapped in `<...>`.  And my own email address in `pq-compile.el` was turned into `***@***.***>` apparently by github.  Feel free to put my real email address in there (or to remove the `Author:` line altogether, since it is only important for the `pq.el` file.

**Comment by monnier** [comment]
Looks great to me, thanks

**Comment by monnier** [comment]
Anything we can do to move this along?

**Comment by marsam** [comment]
Sorry for the delay. 
LGTM, thank you!

**Comment by monnier** [comment]
Thanks, much better.
I just see now that when the package is compiled in batch mode, the new code ends up prompting the (potentially non-existing) user.  And also it may end up "displaying" errors into a buffer instead of into the batch process's output.
So I suggest an additional patch like the one below:

```
diff --git a/.elpaignore b/.elpaignore
new file mode 100644
index 0000000000..955449dbf6
--- /dev/null
+++ b/.elpaignore
@@ -0,0 +1 @@
+pq-test.el
diff --git a/pq-compile.el b/pq-compile.el
index 5899ce7620..b16a06f659 100644
--- a/pq-compile.el
+++ b/pq-compile.el
@@ -37,21 +37,28 @@
       (if (zerop exitcode)
           (message "Compilation of `pq-core' succeeded")
         (let ((out (buffer-string)))
-          (with-current-buffer (get-buffer-create "*pq-compile*")
-            (setq default-directory pq--compile-directory)
-            (let ((inhibit-read-only t))
-              (erase-buffer)
-              (insert out))
-            (compilation-mode)
-            (pop-to-buffer (current-buffer))
-            (error "Compilation of `pq-core' failed")))))))
+          (if noninteractive
+              (message "Compilation of `pq-core' failed:\n%s" out)
+            (with-current-buffer (get-buffer-create "*pq-compile*")
+              (setq default-directory pq--compile-directory)
+              (let ((inhibit-read-only t))
+                (erase-buffer)
+                (insert out))
+              (compilation-mode)
+              (pop-to-buffer (current-buffer))
+              (error "Compilation of `pq-core' failed"))))))))
 
 (defun pq--compile-maybe ()
-  ;; FIXME: Should we first try it silently (i.e. without prompting the user)?
-  (if (not (y-or-n-p "PQ needs to compile the `pq-core' module.  Do it now?"))
-      (message "Continuing without `pq-core'; some operations may fail")
+  (cond
+   (noninteractive ;; Batch use: try to compile but delay errors when possible.
+    (ignore-errors (pq--compile-module))
+    (require 'pq-core nil t))
+   ;; FIXME: Should we first try it silently (i.e. without prompting the user)?
+   ((not (y-or-n-p "PQ needs to compile the `pq-core' module.  Do it now?"))
+    (message "Continuing without `pq-core'; some operations may fail"))
+   (t
     (pq--compile-module)
-    (require 'pq-core)))
+    (require 'pq-core))))
 
 
 (provide 'pq-compile)
```

**Comment by marsam** [comment]
Hi, I'm so sorry for the late response. Somehow your message got lost in my notifications.

I applied your suggestions in 377f408a567a73781490885756b111f4658e1c2d maintaining you as author. Thank you!

**Comment by monnier** [comment]
> I applied your suggestions in 377f408a567a73781490885756b111f4658e1c2d
> maintaining you as author. Thank you!

Looks good, thank you!

**Pull request merged**
